### ISSUE TITLE
Vinix Is Fully Clone Of Lyre

### ISSUE THREAD

**Issue by emma-eva** [vlang/vinix#106]
is it true? Just written some module in v.

v also cloned from others.

**Comment by lukflug** [comment]
I think it's more that both OSes were largely designed and implemented by the same person.

**Comment by exxjob** [comment]
[🤔](https://github.com/vlang/vinix/commit/f7bfc47a491c1c8b79138e3ebd9d5a595fcab267)

**Comment by spytheman** [comment]
If you had made the effort to investigate just a little @emma-eva, you would had seen what came first, and what came second. `git log` is a useful tool for that. So is the github's commit history.
