### ISSUE TITLE
can't build on raspberry pi debian

### ISSUE THREAD

**Issue by Ccode-lang** [vlang/vinix#19]
The distro will not build on raspberry pi so there is no way to build the kernel.

**Comment by AnLAdmin** [comment]
Well, you could use the docker file in the pull request #17 from alii.

**Comment by Ccode-lang** [comment]
Haven't tried to use docker for any project so I don't know how to do that.

**Comment by Ccode-lang** [comment]
Used that now it does not work.

**Comment by Ccode-lang** [comment]
Looks like it was officially dockerized I'll try again with the official one.

**Comment by Ccode-lang** [comment]
Still not working

**Comment by maks** [comment]
I see no evidence that this project supports ARM, there is only a `x86` folder (sic) in the kernel source. Likewise Docker is not some  sort of magic, its simply a nice wrapper around cgroups on Linux. Unless the Docker container that you are referring to has in it QMEU support to allow running a x86 vinix kernel image on your RPI, that will be of little help.

Given the above, why are you trying to build vinix x86 executable image on a Arm-based RPI?

**Comment by JalonSolov** [comment]
Well, it supports M1 Macs (which are ARM based), ARM asm statements, an ARM version of TCC, etc., so yeah, I think there's ARM support.  However, getting everything to work on a new system can be challenging, as there could be header issues, etc.

@shadowninja55 has some experience with V on a Pi.  Maybe he can help.

**Comment by maks** [comment]
Are we talking about V arm support or Vinix? 
I did notice that just today https://github.com/vlang/v/issues/9284 was closed but that's not the same thing as this OS supporting ARM.

**Comment by maks** [comment]
Also if it is the case that it Vinix supports building on M1 macs then [this part of the Readme](https://github.com/vlang/vinix#building-vinix-on-macos) should perhaps be updated.

**Comment by JalonSolov** [comment]
My apologies - I was commenting on the wrong issue.  You are correct that for now, at least, vinix is x86_64 only.  I don't know why ARM can't be supported in the future, but as of this moment - no ARM support.

**Comment by maks** [comment]
@JalonSolov no worries. I'd actually love to see Vinix supporting Arm, especially being able to run on something like the ArmV6 based RPI Zero would be great, as its more like a giant microcontroller then a "mini pc" the way the larger multicore ARMv7 based  RPIs are.

**Comment by Ccode-lang** [comment]
it seems to be working now

**Comment by Ccode-lang** [comment]
nevermind it crashed

**Comment by mintsuki** [comment]
I am not even sure any of the Raspberry Pi models even have the resources necessary to build the entire distro.

Please just use a prebuilt ISO (can find the link in the README) if you want to test it on a Raspberry Pi.

**Comment by Ccode-lang** [comment]
Actually already did this but wasn't sure if the link was updated anymore. The workflow was removed.
