### ISSUE TITLE
Panic in Virtualbox with Muticore CPUs ,even single core

### ISSUE THREAD

**Issue by bhzhu203** [vlang/vinix#20]
Panic in Virtualbox with Muticore CPUs ,even single core

single core:
![2021-06-22_14-30](https://user-images.githubusercontent.com/3523160/122875407-caf34e80-d366-11eb-8149-b846489c3822.png)

Muticore Cores
![2021-06-22_14-35](https://user-images.githubusercontent.com/3523160/122875671-258caa80-d367-11eb-9454-4cd371c490f1.png)

**Comment by koplenov** [comment]
Single core
![image](https://user-images.githubusercontent.com/25139987/123127995-6eba2880-d453-11eb-8e63-97c458ecc78e.png)

Dual Core
![image](https://user-images.githubusercontent.com/25139987/123128184-99a47c80-d453-11eb-9d88-024c5a56ee92.png)

Tri-core(?)
![image](https://user-images.githubusercontent.com/25139987/123128455-d4a6b000-d453-11eb-8f34-c798bcda5620.png)

Quad core
![image](https://user-images.githubusercontent.com/25139987/123128989-441c9f80-d454-11eb-84b0-8349fce8923a.png)

Quad core again..
![image](https://user-images.githubusercontent.com/25139987/123129357-9362d000-d454-11eb-9ef5-a965b72fd48d.png)


I think such mistakes at this stage of development are quite acceptable and will soon be a different situation :D
