### ISSUE TITLE
Kernel Panic without raising memory for qemu that also causes the console to appear frozen during boot

### ISSUE THREAD

**Issue by Wazubaba** [vlang/vinix#24]
I'm not sure if this is something specific to my system or not, but I had to bump the qemu memory limit in the Makefile to 4G but after that it booted (though bash is complaining about no job control). I run a somewhat out of date void linux install, if that makes any difference.

There's also an issue that the OS's console doesn't show any sign of the panic - I had to check the terminal I ran `make run-kvm` in to find out it was panicked. I managed to trigger another panic later (I hit `up` in bash to get the last entered line. Error was: `array.get: index out of range (i == 72, a.len == 58)`) which *did* show the panic info, so this might be some edge-case or something.

Also, I just want to say, this is the first OS I've found written in one of these newer languages that actually builds and runs. Best of all I didn't have to deal with the whole "build your own cross-compilation setup by hand because it needs a specific version of GCC" task only to be greeted with cryptic compile errors that wind up being broken code due to their compiler/stdlib internals changing. I cannot begin to convey my awe at this. Extremely well done.

**Comment by mintsuki** [comment]
As of 755981c, panics will print output to the graphical console.

As for the up arrow issue, I am perfectly aware of this and it is caused by the console not handling arrow keys and special keys in general yet. I will work on this ASAP because a lot of people trigger it accidentally lol

Thanks for the compliments!
