### ISSUE TITLE
trying to move cursor in nano inserts capital letters

### ISSUE THREAD

**Issue by Ccode-lang** [vlang/vinix#41]
this makes nano pretty much unusable

**Comment by Ccode-lang** [comment]
I found that using ^f as -> and ^b as <- works but saving does not save correctly.

**Comment by Ccode-lang** [comment]
![Snip20210907_2](https://user-images.githubusercontent.com/78437178/132442342-47ac1c77-fc15-485f-b730-5bc4c9dd8ffc.png)
It works well for the hello.c file.  This is after using the shortcuts above to use nano to edit hello.c.

**Comment by Ccode-lang** [comment]
^p also works as up arrow but I have not found a shortcut for the down arrow.

**Comment by streaksu** [comment]
The arrow issue was fixed with the latest terminal code updates and now work perfectly, the newline is an issue related to timing that is being worked on right now, will close the issue when done.

**Comment by mintsuki** [comment]
Fixed.
