### ISSUE TITLE
shell: Number of characters per line limited by screen

### ISSUE THREAD

**Issue by koplenov** [vlang/vinix#51]
Error when characters reach the end of the screen:
![image](https://user-images.githubusercontent.com/25139987/132248095-9d4d9c42-ad8c-44a9-9f74-27370c6e8883.png)

**Comment by Ccode-lang** [comment]
I tested, I have the same problem.

**Comment by mintsuki** [comment]
This is an issue related to bash+mlibc, where when wrapping should occur, a segmentation fault happens instead. Managarm OS (which also uses mlibc) suffers from this same issue so it's not a Vinix-specific issue.

Will keep this issue open and close it once it is fixed upstream.

**Comment by mintsuki** [comment]
This must have been fixed on the mlibc upstream at some point. Closing as completed.
