### ISSUE TITLE
when booting it does not count cores right (sometimes)

### ISSUE THREAD

**Issue by Ccode-lang** [vlang/vinix#52]
It was counting cores and said there were 3 when I had it set to 4.  I loaded again and it was right.

**Comment by Ccode-lang** [comment]
when it says three it then hang forever

**Comment by mintsuki** [comment]
Are you passing any special flags to qemu, or more generally, which emulator are you using and how are you invoking it?

**Comment by Ccode-lang** [comment]
I'm using the run command that I put together from the Makefile

**Comment by Ccode-lang** [comment]
I stored it in Ccode-lang/vinix-tester

**Comment by mintsuki** [comment]
Does this still happen with the latest ISO?

**Comment by Ccode-lang** [comment]
Yes.

**Comment by mintsuki** [comment]
I can't reproduce. What is your host system (hardware and OS) and qemu version?

**Comment by Ccode-lang** [comment]
hardware: MacBook Air
Chip: Apple M1
Qemu version: 6.1.0

**Comment by Ccode-lang** [comment]
Maybe it is a problem with qemu and M1?

**Comment by StaticSaga** [comment]
It could very well be a QEMU problem, it works fine on any x86 machine I've tried

**Comment by Ccode-lang** [comment]
I agree M1 is new and could be the problem
