### ISSUE TITLE
does net.http v module work in vinix?

### ISSUE THREAD

**Issue by Ccode-lang** [vlang/vinix#56]
I was wondering because I was going to make a file downloader for vinix.  Maybe once it works we could add it to vinix.

**Comment by ama-coder** [comment]
no . vinix dosent have a network driver

**Comment by medvednikov** [comment]
(yet) :)

**Comment by Ccode-lang** [comment]
Ok 👍

**Comment by Ccode-lang** [comment]
I'll save the idea for a package manager for later.
