### ISSUE TITLE
[DOCS] - Discord chat url is invalid

### ISSUE THREAD

**Issue by sloorush** [vlang/vinix#65]
I was trying to join the discord chat, the URL to join the server has expired.

![image](https://user-images.githubusercontent.com/54478821/139595292-d3a01287-6573-4369-8e49-c5c778808cc1.png)

**Comment by r4v10l1** [comment]
You should also update/add the [new vinix invite](https://discord.com/invite/S5Nm6ZDU38) on the [vinix-os](http://vinix-os.org) website (still has the vlang invite).

**Comment by FrostyTheSouthernSnowman** [comment]
Fixed the issue last night. Thank you for reporting it.
