### ISSUE TITLE
How to boot vinix in qemu(windows)?

### ISSUE THREAD

**Issue by bistcuite** [vlang/vinix#69]
How can i boot vinix on windows with qemu ?

**Comment by Ccode-lang** [comment]
qemu-system-x86_64 -cpu qemu64,level=11,+rdtscp -M q35,smm=off -m 8G -smp 4 -cdrom os.iso -serial stdio -no-shutdown -no-reboot

**Comment by Ccode-lang** [comment]
Replace os.iso with the name of the iso you got from the Vinix build server.
