### ISSUE TITLE
Win kernel

### ISSUE THREAD

**Issue by ddkwork** [vlang/vinix#90]
How to write a windows kernel driver hook ssdt table with vt-x ept page hide use vlang

**Comment by Dennisbonke** [comment]
What? Doesn't seem related to Vinix at all, also doesn't seem to be correct English. Try again?

**Comment by ddkwork** [comment]
> What? Doesn't seem related to Vinix at all. This isn't windows kernel development.

any winapi binded?

**Comment by JalonSolov** [comment]
Why would there be an winapi binding, when this is a Linux compatible kernel?
